version: '3.7'

services:
  books_app:
    container_name: books_microservice
    restart: always
    build: ./books
    image: francescolbn/books_microservice
    ports: ['5757:5757']
    entrypoint: '/bin/bash -c'
    command:
      - |
        npm install
        npm start
    links:
      - mongodb_docker
    volumes:
      - ./books:/app:delegated

  customers_app:
    container_name: customers_microservice
    restart: always
    build: ./customers
    image: francescolbn/customers_microservice
    ports: ['7575:7575']
    entrypoint: '/bin/bash -c'
    command:
      - |
        npm install
        npm start
    links:
      - mongodb_docker
    volumes:
      - ./customers:/app:delegated

  orders_app:
    container_name: orders_microservice
    restart: always
    build: ./orders
    image: francescolbn/orders_microservice
    ports: ['7777:7777']
    entrypoint: '/bin/bash -c'
    command:
      - |
        npm install
        npm start
    links:
      - mongodb_docker
    volumes:
      - ./orders:/app/orders:delegated

  mongodb_docker:
    container_name: mongodb_container
    image: mongo
    ports:
      - '27017:27017'
