version: '3.7'

services:
  nodejs_app:
    container_name: nodejs_microservice
    restart: always
    build: ./server
    image: francescolbn/nodejs_microservice
    ports: ['5757:5757']
    entrypoint: '/bin/bash -c'
    command:
      - |
        npm install
        npm start
    links:
      - mongodb_docker
    volumes:
      - ./server:/app:delegated

  mongodb_docker:
    container_name: mongodb_container
    image: mongo
    ports:
      - '27017:27017'
